all : ; > po4a/po/pt_BR.po && po4a --verbose -o no-warn po4a.conf
#clean : ; unlink po4a/po/pt_BR.po; unlink texinfo/translated/texinfo-ed.7.1-pt_BR.texi
#copy : ; rclone copy /home/jamenson/repos/espindula/testes/ /home/jamenson/repos/espindula/gnuti/
